when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
    # set the language for foundry Faker method
        faker:
            locale: fr_FR
when@test: *dev

        